### ISSUE TITLE
No data or graphs visible

### ISSUE THREAD

**Issue by spandan13** [kdkasad/vnstat-web#1]
I was testing this out by cloning the repo and just serving it using `php -S localhost:8080` command. The page loads up but no graphs are visible. 
![image](https://user-images.githubusercontent.com/100998511/189673744-b1777556-fbc2-4cf4-93af-831ea08dfefe.png)

**Comment by kdkasad** [comment]
Can you post any logs from the PHP server as well as any errors that appear in the web browser's console?

**Edit:** also include which version of vnstat is being used. Ensure that data is available when using the `vnstat(1)` command, as it's possible that the issue is in the vnstat configuration rather than in vnstat-web.

**Comment by spandan13** [comment]
Fixed the issue by installing and using apache webserver instead of php.
